export interface TasksItems {
    assignee: string,
    challanid: string,
    comments: string,
    customer_contact: string,
    customer_id: string,
    customername: string,
    customer_sign_link: string,
    customer_sign_time: Date,
    expected_time: Date,
    id: number,
    instructions: string,
    location: string,
    orderid: string,
    product_name: string,
    quantity: number,
    route: string,
    status: string,
    task_seq: number,
    task_type: string,
    createdBy?:string,
      createdDate?:Date,
      lastModifiedBy?:string,
      lastModifiedDate?: Date
    }